apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ws-app.fullname" . }}-config

data:
  default.yaml: |
    kafka:
      brokers:
        - kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092
        - kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092
        - kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092
      topics:
        customerCreated: customer-created
        customerGetById: customer-get-by-id
        customersGet: customer-get
        dataSaved: data-saved

